### ISSUE TITLE
ClimaCoreVTK: time series output for Cartesian spaces

### ISSUE THREAD

**Issue by valeriabarra** [CliMA/ClimaCore.jl#589]
Do we have vtk time series capability for Cartesian spaces (i.e., simple rectangle, hybrid 2d, hybrid 3d)?
I tried it and I saw an error. I often double-check the syntax with unit tests, but it looks like we are missing time series vtk output tests for all Cartesian spaces (i.e., simple rectangle, hybrid 2d, hybrid 3d).

(I personally need this to be able to visualize in paraview the Cartesian 3D hybrid limiters example I am working on, but I think it would be useful in general).

**Comment by simonbyrne** [comment]
Can you give a simple reproducible example, and the stack trace?

**Comment by valeriabarra** [comment]
For a MWE, I created this [branch](https://github.com/CliMA/ClimaCore.jl/tree/valeria/3d-hybrid-vtk-viz), with only a small modification to the existing hybrid 3d bubble to plot the temperature (i.e., a scalar defined on cell centers). I used the `basis: cell` specification that I could see from the single snapshot [unit test](https://github.com/CliMA/ClimaCore.jl/blob/6a1e023df3f0cfdecf617d0da7a617d6fdcf7877/lib/ClimaCoreVTK/test/runtests.jl#L224), and here is the stack trace:

```
julia> include("examples/hybrid/bubble3d_invariant.jl")
ODE 100%|███████████████████████████████████████████████████████████████████████████████| Time: 0:00:12
WARNING: using Plots.coords in module Main conflicts with an existing identifier.
ERROR: LoadError: MethodError: no method matching vtk_grid_space(::Vector{ClimaCore.Fields.Field})
Closest candidates are:
  vtk_grid_space(::ClimaCore.Spaces.SpectralElementSpace1D) at ~/.julia/packages/ClimaCoreVTK/u3e7s/src/space.jl:184
  vtk_grid_space(::ClimaCore.Spaces.SpectralElementSpace2D) at ~/.julia/packages/ClimaCoreVTK/u3e7s/src/space.jl:192
  vtk_grid_space(::ClimaCore.Spaces.ExtrudedFiniteDifferenceSpace{ClimaCore.Spaces.CellFace}) at ~/.julia/packages/ClimaCoreVTK/u3e7s/src/space.jl:200
  ...
Stacktrace:
 [1] #13
   @ ~/.julia/packages/ClimaCoreVTK/u3e7s/src/ClimaCoreVTK.jl:136 [inlined]
 [2] paraview_collection(f::ClimaCoreVTK.var"#13#14"{Base.Pairs{Symbol, Symbol, Tuple{Symbol}, NamedTuple{(:basis,), Tuple{Symbol}}}, String, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, NamedTuple{(:θ,), Tuple{Vector{ClimaCore.Fields.Field}}}, Int64}, args::String; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ WriteVTK ~/.julia/packages/WriteVTK/HCt8Y/src/WriteVTK.jl:166
 [3] paraview_collection
   @ ~/.julia/packages/WriteVTK/HCt8Y/src/WriteVTK.jl:163 [inlined]
 [4] #writevtk#12
   @ ~/.julia/packages/ClimaCoreVTK/u3e7s/src/ClimaCoreVTK.jl:134 [inlined]
 [5] top-level scope
   @ ~/CliMA/ClimaCore.jl/examples/hybrid/bubble3d_invariant.jl:379
 [6] include(fname::String)
   @ Base.MainInclude ./client.jl:451
 [7] top-level scope
   @ REPL[1]:1
in expression starting at /home/valeria/CliMA/ClimaCore.jl/examples/hybrid/bubble3d_invariant.jl:379
```

**Comment by valeriabarra** [comment]
Just for simplicity, I paste here the only addition to the hybrid 3d bubble example I have in this [branch](https://github.com/CliMA/ClimaCore.jl/tree/valeria/3d-hybrid-vtk-viz) that produces the above stack trace:

```
# VTK plot
using ClimaCoreVTK
time_end = 1.0
times = 0:Δt:time_end
Theta_times = Array{Fields.Field}(undef, length(times))
for tt in 1:Int(div(time_end, Δt))
    Theta_times[tt] = sol.u[tt].Yc.ρθ ./ sol.u[tt].Yc.ρ
end
writevtk(
    joinpath(path, "theta"),
    times,
    (θ = Theta_times,);
    basis = :cell,
)
```

**Comment by jakebolewski** [comment]
you need to use `writepvd`?

**Comment by valeriabarra** [comment]
Why in this case `writepvd`? All [unit tests](https://github.com/CliMA/ClimaCore.jl/blob/main/lib/ClimaCoreVTK/test/runtests.jl) use `writevtk`. 

In the absence of examples in our viz lib directories, people refer to unit tests to double-check that they use the right syntax.

**Comment by jakebolewski** [comment]
It's the same issues as https://github.com/CliMA/ClimaCore.jl/issues/537

**Comment by valeriabarra** [comment]
Thanks. It wasn't completely addressed (in fact, we could reopen #537 , as I had only added unit tests for it, but it did not work in the application code). 
I'd asked if we could add unit tests and examples to avoid this confusion, indeed. 
If we want to definitely deprecate `writevtk`, then we should add unit tests for `writepvd` or examples that use `paraview_collection` that people can refer to. If we still support it, then it would be nice if we could figure out what is the issue with that.

**Comment by simonbyrne** [comment]
@valeriabarra Can you give an example that I can run directly (e.g. on a branch)?

**Comment by valeriabarra** [comment]
> @valeriabarra Can you give an example that I can run directly (e.g. on a branch)?

Hi Simon. I linked to the branch above. The branch is [valeria/3d-hybrid-vtk-viz](https://github.com/CliMA/ClimaCore.jl/tree/valeria/3d-hybrid-vtk-viz), and the example is `examples/hybrid/bubble3d_invariant.jl`

**Comment by simonbyrne** [comment]
okay, so the issues are:
- there was a problem in the older version of ClimaCoreVTK: one writevtk method didn't accept the keyword arguments (I had used a `,` instead of a `;`). This was fixed when i renamed it to `writepvd`: 
https://github.com/CliMA/ClimaCore.jl/commit/afab1cdde453435c719d41a2a102374e98de9de6#diff-b2468360909c6312532998a41fb2b70699b3f36040171e304402f3b96fbb2be5L144
- the examples are set up to use the release version of ClimaCoreVTK, not the current development version. I'll fix that.

**Comment by valeriabarra** [comment]
@simonbyrne I rebased my branch onto `main` now that your PR #591 was merged (I did not get a change to test it out while the PR was open and comment/approve it). It seems like it still didn't solve the issue:

```
julia> include("examples/hybrid/bubble3d_invariant.jl")
ODE 100%|████████████████████████████████████████████████████████████████████████████████████| Time: 0:00:13
[ Info: Precompiling ClimaCorePlots [cf7c7e5a-b407-4c48-9047-11a94a308626]
WARNING: using Plots.coords in module Main conflicts with an existing identifier.
[ Info: Precompiling GR_jll [d2c73de3-f751-5644-a686-071e5b155ba9]
[ Info: Precompiling ClimaCoreVTK [c8b6d40d-e815-466f-95ae-c48aefa668fa]
ERROR: LoadError: UndefRefError: access to undefined reference
Stacktrace:
  [1] getindex
    @ ./array.jl:861 [inlined]
  [2] (::ClimaCoreVTK.var"#17#19"{Int64})(::Pair{Symbol, Vector{ClimaCore.Fields.Field}})
    @ ClimaCoreVTK ./none:0
  [3] iterate
    @ ./generator.jl:47 [inlined]
  [4] merge(a::NamedTuple{(), Tuple{}}, itr::Base.Generator{Base.Pairs{Symbol, Vector{ClimaCore.Fields.Field}, Tuple{Symbol}, NamedTuple{(:θ,), Tuple{Vector{ClimaCore.Fields.Field}}}}, ClimaCoreVTK.var"#17#19"{Int64}})
    @ Base ./namedtuple.jl:292
  [5] NamedTuple
    @ ./namedtuple.jl:113 [inlined]
  [6] (::ClimaCoreVTK.var"#16#18"{Base.Pairs{Symbol, Symbol, Tuple{Symbol}, NamedTuple{(:basis,), Tuple{Symbol}}}, String, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, NamedTuple{(:θ,), Tuple{Vector{ClimaCore.Fields.Field}}}, Int64})(pvd::WriteVTK.CollectionFile)
    @ ClimaCoreVTK ~/CliMA/ClimaCore.jl/lib/ClimaCoreVTK/src/ClimaCoreVTK.jl:149
  [7] paraview_collection(f::ClimaCoreVTK.var"#16#18"{Base.Pairs{Symbol, Symbol, Tuple{Symbol}, NamedTuple{(:basis,), Tuple{Symbol}}}, String, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, NamedTuple{(:θ,), Tuple{Vector{ClimaCore.Fields.Field}}}, Int64}, args::String; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ WriteVTK ~/.julia/packages/WriteVTK/HCt8Y/src/WriteVTK.jl:166
  [8] paraview_collection
    @ ~/.julia/packages/WriteVTK/HCt8Y/src/WriteVTK.jl:163 [inlined]
  [9] #writepvd#15
    @ ~/CliMA/ClimaCore.jl/lib/ClimaCoreVTK/src/ClimaCoreVTK.jl:147 [inlined]
 [10] writevtk(basename::String, times::StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, fields::NamedTuple{(:θ,), Tuple{Vector{ClimaCore.Fields.Field}}}; vtkargs::Base.Pairs{Symbol, Symbol, Tuple{Symbol}, NamedTuple{(:basis,), Tuple{Symbol}}})
    @ ClimaCoreVTK ./deprecated.jl:72
 [11] top-level scope
    @ ~/CliMA/ClimaCore.jl/examples/hybrid/bubble3d_invariant.jl:379
 [12] include(fname::String)
    @ Base.MainInclude ./client.jl:451
 [13] top-level scope
    @ REPL[1]:1
in expression starting at /home/valeria/CliMA/ClimaCore.jl/examples/hybrid/bubble3d_invariant.jl:379
```

**Comment by valeriabarra** [comment]
Or there is another issue

**Comment by jakebolewski** [comment]
your time vector and state field vector lengths don't match

**Comment by valeriabarra** [comment]
> your time vector and state field vector lengths don't match

woops! I'll double check that. Sorry for silly mismatching!

**Comment by valeriabarra** [comment]
I had ported over different parts of examples to make the minimal example branch. 

I can confirm now that it works!
