### ISSUE TITLE
Level of FiniteDifferenceSpace not behaving as expected

### ISSUE THREAD

**Issue by kmdeck** [CliMA/ClimaCore.jl#869]
## Describe the bug
The level of a FiniteDifferenceSpace is a PointSpace. We should be able to call functions taking a space as an argument on a PointSpace. The function ClimaCore.Fields.zeros(p::PointSpace) has unexpected behavior.
## To Reproduce
```
julia> column = ClimaCore.Domains.IntervalDomain(
           ClimaCore.Geometry.ZPoint{FT}(-10.0),
           ClimaCore.Geometry.ZPoint{FT}(0.0);
           boundary_tags = (:top, :bottom)
       );

julia> mesh = ClimaCore.Meshes.IntervalMesh(column; nelems = 10);

julia> center_space = ClimaCore.Spaces.CenterFiniteDifferenceSpace(mesh);

julia> face_space = ClimaCore.Spaces.FaceFiniteDifferenceSpace(center_space);

julia> surface_space = ClimaCore.Fields.level(face_space, ClimaCore.Spaces.nlevels(face_space));

julia> ClimaCore.Fields.zeros(surface_space)
ERROR: MethodError: no method matching parent_array_type(::Type{Base.ReshapedArray{Float64, 2, SubArray{Float64, 1, Matrix{Float64}, Tuple{Int64, Base.Slice{Base.OneTo{Int64}}}, true}, Tuple{}}})
Closest candidates are:
  parent_array_type(::Type{<:Array{T}}) where T at ~/.julia/packages/ClimaCore/7zddI/src/DataLayouts/struct.jl:89
  parent_array_type(::Type{<:StaticArraysCore.MArray{S, T, N, L}}) where {S, T, N, L} at ~/.julia/packages/ClimaCore/7zddI/src/DataLayouts/struct.jl:90
  parent_array_type(::Type{<:SubArray{T, N, A}}) where {T, N, A} at ~/.julia/packages/ClimaCore/7zddI/src/DataLayouts/struct.jl:92
  ...
Stacktrace:
 [1] parent_array_type(#unused#::Type{SubArray{Float64, 2, Base.ReshapedArray{Float64, 2, SubArray{Float64, 1, Matrix{Float64}, Tuple{Int64, Base.Slice{Base.OneTo{Int64}}}, true}, Tuple{}}, Tuple{Base.Slice{Base.OneTo{Int64}}, UnitRange{Int64}}, true}})
   @ ClimaCore.DataLayouts ~/.julia/packages/ClimaCore/7zddI/src/DataLayouts/struct.jl:92
 [2] similar(bc::ClimaCore.DataLayouts.DataF{ClimaCore.Geometry.ZPoint{Float64}, SubArray{Float64, 2, Base.ReshapedArray{Float64, 2, SubArray{Float64, 1, Matrix{Float64}, Tuple{Int64, Base.Slice{Base.OneTo{Int64}}}, true}, Tuple{}}, Tuple{Base.Slice{Base.OneTo{Int64}}, UnitRange{Int64}}, true}}, #unused#::Type{Float64})
   @ ClimaCore.DataLayouts ~/.julia/packages/ClimaCore/7zddI/src/DataLayouts/broadcast.jl:227
 [3] ClimaCore.Fields.Field(#unused#::Type{Float64}, space::ClimaCore.Spaces.PointSpace{ClimaCore.DataLayouts.DataF{ClimaCore.Geometry.LocalGeometry{(3,), ClimaCore.Geometry.ZPoint{Float64}, Float64, StaticArraysCore.SMatrix{1, 1, Float64, 1}}, Base.ReshapedArray{Float64, 2, SubArray{Float64, 1, Matrix{Float64}, Tuple{Int64, Base.Slice{Base.OneTo{Int64}}}, true}, Tuple{}}}})
   @ ClimaCore.Fields ~/.julia/packages/ClimaCore/7zddI/src/Fields/Fields.jl:32
 [4] zeros(#unused#::Type{Float64}, space::ClimaCore.Spaces.PointSpace{ClimaCore.DataLayouts.DataF{ClimaCore.Geometry.LocalGeometry{(3,), ClimaCore.Geometry.ZPoint{Float64}, Float64, StaticArraysCore.SMatrix{1, 1, Float64, 1}}, Base.ReshapedArray{Float64, 2, SubArray{Float64, 1, Matrix{Float64}, Tuple{Int64, Base.Slice{Base.OneTo{Int64}}}, true}, Tuple{}}}})
   @ ClimaCore.Fields ~/.julia/packages/ClimaCore/7zddI/src/Fields/Fields.jl:213
 [5] zeros(space::ClimaCore.Spaces.PointSpace{ClimaCore.DataLayouts.DataF{ClimaCore.Geometry.LocalGeometry{(3,), ClimaCore.Geometry.ZPoint{Float64}, Float64, StaticArraysCore.SMatrix{1, 1, Float64, 1}}, Base.ReshapedArray{Float64, 2, SubArray{Float64, 1, Matrix{Float64}, Tuple{Int64, Base.Slice{Base.OneTo{Int64}}}, true}, Tuple{}}}})
   @ ClimaCore.Fields ~/.julia/packages/ClimaCore/7zddI/src/Fields/Fields.jl:218
 [6] top-level scope
   @ REPL[9]:1
 [7] top-level scope
   @ ~/.julia/packages/CUDA/DfvRa/src/initialization.jl:52
```

**Comment by charleskawczynski** [comment]
#876 should fix this, but note that 
```julia
surface_space = ClimaCore.Fields.level(face_space, ClimaCore.Spaces.nlevels(face_space));
```
must become
```julia
surface_space = ClimaCore.Fields.level(face_space, ClimaCore.Utilities.PlusHalf(ClimaCore.Spaces.nlevels(face_space)-1));
# or
surface_space = ClimaCore.Fields.level(face_space, ClimaCore.Utilities.PlusHalf(ClimaCore.Spaces.nlevels(center_space)));
```
IIRC, the logic behind this is that 0 (the surface) is before 1 (the first level). Also note that `nlevels(center_space) + 1 == nlevels(face_space)`.

**Comment by kmdeck** [comment]
@charleskawczynski I think this error still occurs. Im using ClimaCore commit   [d414da3d] ClimaCore v0.10.8 `https://github.com/CliMA/ClimaCore.jl.git#e9aae01` now but still getting the error (using the correct 
```surface_space = ClimaCore.Fields.level(face_space, ClimaCore.Utilities.PlusHalf(ClimaCore.Spaces.nlevels(face_space)-1));```

**Comment by kmdeck** [comment]
(the other bug discussed on slack is fixed as shown by the test you wrote!)

**Comment by charleskawczynski** [comment]
That's weird, it worked for me. Did you `] dev .` from `ClimaCore.jl/` after checking out the commit?

**Comment by kmdeck** [comment]
hmm, I just did
(ClimaLSM) pkg> rm ClimaCore
(ClimaLSM) pkg > add ClimaCore#e9aae014699b435d54d9dd8f42092ce0a077464b
(ClimaLSM) pkg> status ClimaCore
     Project ClimaLSM v0.1.0
      Status `~/Desktop/code/ClimaLSM.jl/Project.toml`
  [d414da3d] ClimaCore v0.10.8 `https://github.com/CliMA/ClimaCore.jl.git#e9aae01`


and also in test:
(test) pkg> status ClimaCore
      Status `~/Desktop/code/ClimaLSM.jl/test/Project.toml`
  [d414da3d] ClimaCore v0.10.8 `https://github.com/CliMA/ClimaCore.jl.git#e9aae01`

**Comment by charleskawczynski** [comment]
Ok, I'll take another look

**Comment by charleskawczynski** [comment]
Ahh, everything works except for `ClimaCore.Fields.zeros(surface_space)`.

**Comment by kmdeck** [comment]
You probably already saw, but I think this is because `Fields.Field(FT, surface_space)` fails, which in turn fails because `similar(ClimaCore.Spaces.coordinates_data(surface_space))` fails...

**Comment by charleskawczynski** [comment]
Let's open up a separate issue about the zeros / similar on point spaces.
